version: '2'
services:
    pruebaentidad-app:
        image: pruebaentidad
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://pruebaentidad-mysql:3306/pruebaentidad?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    pruebaentidad-mysql:
        extends:
            file: mysql.yml
            service: pruebaentidad-mysql
